create table public.users
(
    user_id            bigint generated by default as identity
        primary key,
    slack_id           varchar(100)            not null
        unique,
    baekjoon_id        varchar(100)            not null
        unique,
    user_name          varchar(50)             not null,
    boj_tier           varchar(100)            not null,
    team_name          varchar(50)             not null,
    total_solved_count integer   default 0     not null,
    is_alert_agreed    boolean   default true  not null,
    created_at         timestamp default now() not null,
    updated_at         timestamp default now() not null,
    deleted_at         timestamp
);

