create table if not exists public.problem
(
    problem_id    bigint  not null
        primary key,
    problem_title varchar(255),
    problem_level integer not null,
    problem_url   varchar(500)
);

create table if not exists public.problem_type
(
    problem_type_id   bigint not null
        primary key,
    problem_type_name varchar(100) not null
);

create table if not exists public.problem_problem_type
(
    problem_type_id bigint not null
        constraint fk_ptm_type
            references public.problem_type,
    problem_id      bigint not null
        constraint fk_ptm_problem
            references public.problem
);

create table public.users
(
    user_id            bigint generated by default as identity
        primary key,
    slack_id           varchar(100)            not null
        unique,
    baekjoon_id        varchar(100)            not null
        unique,
    user_name          varchar(50)             not null,
    boj_tier           varchar(100)            not null,
    team_name          varchar(50)             not null,
    total_solved_count integer   default 0     not null,
    is_alert_agreed    boolean   default true  not null,
    created_at         timestamp default now() not null,
    updated_at         timestamp default now() not null,
    deleted_at         timestamp
);


create table public.users_problem
(
    user_id          bigint                not null
        constraint fk_up_user
            references public.users,
    problem_id       bigint                not null
        constraint fk_up_problem
            references public.problem,
    is_solved        boolean default false not null,
    solved_time      timestamp
);

CREATE UNIQUE INDEX idx_user_problem_unique
    ON public.users_problem (user_id, problem_id);


