create table if not exists public.problem
(
    problem_id    bigint  not null
        primary key,
    problem_title varchar(255),
    problem_level integer not null,
    problem_url   varchar(255)
);



create table if not exists public.problem_type
(
    problem_type_id   bigint generated by default as identity
        primary key,
    problem_type_name varchar(100) not null
);


create table if not exists public.problem_problem_type
(
    problem_type_id         bigint not null
        constraint fk_ptm_type
            references public.problem_type,
    problem_id              bigint not null
        constraint fk_ptm_problem
            references public.problem,
    problem_problem_type_id bigint generated by default as identity,
    constraint uk_problem_type_problem
        unique (problem_type_id, problem_id)
);


create index if not exists idx_problem_type
    on public.problem_problem_type (problem_type_id);

create table if not exists public.users
(
    user_id            bigint generated by default as identity
        primary key,
    slack_id           varchar(255)            not null
        unique,
    baekjoon_id        varchar(255)            not null
        unique,
    user_name          varchar(50)             not null,
    boj_tier           integer                 not null,
    team_name          varchar(255)            not null,
    total_solved_count integer   default 0     not null,
    is_alert_agreed    boolean   default true  not null,
    created_at         timestamp default now() not null,
    updated_at         timestamp default now() not null,
    deleted_at         timestamp
);


create table if not exists public.users_problem
(
    users_problem_id bigint generated by default as identity
        primary key,
    user_id          bigint                not null
        constraint fk_up_user
            references public.users,
    problem_id       bigint                not null
        constraint fk_up_problem
            references public.problem,
    is_solved        boolean default false not null,
    solved_time      timestamp
);


