project:
  name: Worker
  version: 1.0.0
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration.class
  config:
    import:
      - postgres.yml
      - mongo.yml
      - batch.yml
  application:
    name: worker

logging:
  level:
    root: INFO
    org.springframework.batch: INFO
    com.midas.worker: INFO


---

spring:
  config:
    activate:
      on-profile: local
logging:
  level:
    root: DEBUG
    com.midas.worker: DEBUG
    org.springframework.batch: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

---

spring:
  config:
    activate:
      on-profile: dev
logging:
  level:
    root: INFO
    org.springframework.batch: INFO
    com.midas.worker: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
