# application.yml
project:
  name: Worker
  version: 1.0.0

spring:
  config:
    import:
      - postgres.yml
      - mongo.yml
      - batch.yml
  application:
    name: worker

solved:
  api:
    user-info: https://solved.ac/api/v3/user/show
    problem-info: https://solved.ac/api/v3/search/problem

slack:
  enabled: true
  color:
    green: '#36a64f'
    red: '#ff0000'
    yellow: '#ffcc00'
    blue: '#0070ce'

logging:
  level:
    root: INFO
    org.springframework.batch: INFO
    com.midas.worker: INFO

---
spring:
  config:
    activate:
      on-profile: local

slack:
  webhook:
    url: http://localhost/dummy
  enabled: false

logging:
  level:
    root: DEBUG
    com.midas.worker: DEBUG
    org.springframework.batch: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

---
spring:
  config:
    activate:
      on-profile: dev

slack:
  webhook:
    url: ${SLACK_WEBHOOK_URL}
  enabled: true

logging:
  level:
    root: INFO
    org.springframework.batch: INFO
    com.midas.worker: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

---
spring:
  config:
    activate:
      on-profile: prod

slack:
  webhook:
    url: ${SLACK_WEBHOOK_URL}
  enabled: true

logging:
  level:
    root: WARN
    org.springframework.batch: WARN
    com.midas.worker: INFO