spring:
  data:
    mongodb:
      auto-index-creation: true
      uri: ${MONGO_URI:}
      username: ${MONGO_USER_NAME:}
      password: ${MONGO_PASSWORD:}


logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.mongodb.driver.protocol.command: DEBUG
    org.mongodb.driver.connection: DEBUG

---
spring.config.activate.on-profile: local

spring:
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://localhost:27017/app

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: INFO
    org.mongodb.driver.protocol.command: INFO
    org.mongodb.driver.connection: INFO
