# mongo.yml
spring:
  data:
    mongodb:
      auto-index-creation: true

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.mongodb.driver.protocol.command: DEBUG
    org.mongodb.driver.connection: DEBUG

---
spring.config.activate.on-profile: local

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: app

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: INFO
    org.mongodb.driver.protocol.command: INFO
    org.mongodb.driver.connection: INFO

---
spring.config.activate.on-profile: prod

spring:
  data:
    mongodb:
      uri: ${MONGO_URL}
      database: ${MONGO_DATABASE}
      username: ${MONGO_USER_NAME}
      password: ${MONGO_PASSWORD}
      auto-index-creation: false

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: WARN
    org.mongodb.driver.protocol.command: WARN
    org.mongodb.driver.connection: WARN
