# postgres.yml
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      max-lifetime: 300000
      validation-timeout: 5000
      keepalive-time: 30000

---
spring.config.activate.on-profile: local

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/app
    username: kimdoyeon
    password: ""

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.sql: DEBUG
    org.hibernate.type: TRACE
    com.zaxxer.hikari.HikariConfig: DEBUG
    org.postgresql: TRACE
---
spring.config.activate.on-profile: prod

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

logging:
  level:
    org.hibernate.sql: WARN